version: '3'

services:
  exercism:
    build: .
    image: brainpower/ocaml-exercism-cubicle
    ports:
      - '8443:8443'
    volumes:
      - ".:/repo"
      - "$SSH_AUTH_SOCK:/ssh-agent"
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    command: code-server --allow-http --no-auth /repo
