version: '3'

services:
  exercism:
    build: .
    image: brainpower/ocaml-exercism-cubicle
    ports:
      - '8443:8443'
    volumes:
      - ".:/repo"
    command: code-server --allow-http --no-auth /repo