
version: 2
jobs:
  build:
    docker:
      - image: brainpower/ocaml-exercism-cubicle
    working_directory: /exercism/ocaml
    steps:
      - checkout:
          path: /checkout
      - run:
          name: Sync
          command: cp -r /checkout/. /exercism/ocaml
      - run:
          name: Test
          command: dune runtest
