
version: 2
jobs:
  build:
    docker:
      - image: brainpower/ocaml-exercism-cubicle
    working_directory: /repo
    steps:
      - checkout:
          path: ~/checkout
      - run:
          name: Sync
          command: cp -rf ~/checkout/* /repo/ && chown -R opam:opam /repo
      - run:
          name: Test hello-world
          command: source ~/.profile && cd exercises/hello-world && dune runtest
