
version: 2
jobs:
  build:
    docker:
      - image: brainpower/ocaml-exercism-cubicle
    working_directory: /exercism/ocaml
    steps:
      - checkout:
          path: /checkout
      - run:
          name: Sync
          command: cp -r /checkout/. /repo/
      - run:
          name: Test hello-world
          command: cd exercises/hello-world && dune runtest
